name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Welcome to the project! Thanks for opening an issue. We appreciate your interest.'
          pr-message: 'Welcome to the project! Thanks for your contribution. We will review your PR soon.'
